<?php //006ef
// This Software is the property of D³ Data Development and is protected by copyright law - it is NOT Freeware.  Any unauthorized use of this software without a valid license key is a violation of the license agreement and will be prosecuted by civil and criminal law.  Inhaber: Thomas Dartsch Alle Rechte vorbehalten  @package LoginAsCustomer @version 3.0.1.3 PHP71 (04.01.2021) @author  Daniel Seifert support@shopmodule.com @copyright (C) 2021, D3 Data Development @see http://www.shopmodule.com
if(!extension_loaded('ionCube Loader')){$__oc=strtolower(substr(php_uname(),0,3));$__ln='ioncube_loader_'.$__oc.'_'.substr(phpversion(),0,3).(($__oc=='win')?'.dll':'.so');if(function_exists('dl')){@dl($__ln);}if(function_exists('_il_exec')){return _il_exec();}$__ln='/ioncube/'.$__ln;$__oid=$__id=realpath(ini_get('extension_dir'));$__here=dirname(__FILE__);if(strlen($__id)>1&&$__id[1]==':'){$__id=str_replace('\\','/',substr($__id,2));$__here=str_replace('\\','/',substr($__here,2));}$__rd=str_repeat('/..',substr_count($__id,'/')).$__here.'/';$__i=strlen($__rd);while($__i--){if($__rd[$__i]=='/'){$__lp=substr($__rd,0,$__i).$__ln;if(file_exists($__oid.$__lp)){$__ln=$__lp;break;}}}if(function_exists('dl')){@dl($__ln);}}else{die('The file '.__FILE__." is corrupted.\n");}if(function_exists('_il_exec')){return _il_exec();}echo("Site error: the ".(php_sapi_name()=='cli'?'ionCube':'<a href="http://www.ioncube.com">ionCube</a>')." PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.\n\nPlease visit ".(php_sapi_name()=='cli'?'get-loader.ioncube.com':'<a href="http://get-loader.ioncube.com">get-loader.ioncube.com</a>')." for install assistance.\n\n");exit(199);
?>
HR+cPv+maQUfdcg8j0G4XDuXVnQiVjbS93VqTCwY10iPqGXEmL/Hff95MPOvzTnkpCZ4LKSUKQFf
ll+EBK2F5YqEtHmco5MR4jDzp5UEt4eVmqMP+WMGMNKauvLOG8c/ySQha6o0X/i4IzBVZ/bIcwTv
UHFEn8q9XwFvtAdDsdwp08sz2ndmTofmtaLc6yX4UtKgwC6b4XlerB+url8LxDJy8+8lgy4tIEpr
jdcNyw25y57Q51OE37b2XpCo0r3DdXKchZVRI+8sv5fT0BC+zx5Wd2D8QzyPQun31Yd4evY7ZCEi
jAwZB5ArlOEobjIPPqvmHfmiftoMnp7wKHm5MFOg4LngzDN/5pIdDWvA69GD91bFneCOfm6idY9G
S/SWnI2XO07Oaplj+FkgAPJerI53Qi3TMG7lX2OUZ6OddNePB3j1CWeVaBuUtkULM8WerF13g2nh
0wWD8hHTh7W3xhDIrbUczOBcO5iXT7l3NDFsbgs6hlihxBifhhnMe44fVx3Abk/ZLP707l5EUAw4
tKdNcsSaoVRCX0lNHgZTXWJNIekZjPTRkX4cxFe19e4VIeTZYN2Vv+ZNvRFTKV8MG+6HSqwNG7Uj
q8H+G6i/2fMBlmoEupAXJDEgTa6aO7dWHG==